version: '3.3'
services:

  db:
    image: "postgres:9.6.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    networks:
      - chatBot
    volumes:
        - db:/var/lib/postgresql/data

volumes:
  db:
      external:
          name: chatBot-db

networks:
    magnit:
        external:
            name: chatBot