version: '3'
services:

  postgres:
    image: "postgres:9.6.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  bakend:
    image: node:10-alpine
    volumes:
      - .:/devel
    working_dir: /devel/packages/backend
    command: npm run start:dev
    restart: always
    ports:
      - "8000:8000"
    depends_on: 
      - postgres

volumes:
  postgres:
    external:
      name: postgres

